on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on:
      group: fuzzer
    environment: fuzzer
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - run: export FOUNDRY_DIR=$HOME/.local && curl -L https://foundry.paradigm.xyz | bash && foundryup
      - run: yarn
      - run: yarn lint
      - run: yarn coverage
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.info,coverage/lcov.info
